import pygame
icon = pygame.image.load("Sprites/icon.png")
playerImg = pygame.image.load("Sprites/Batydar.png")
keyboardImg = pygame.image.load("Sprites/Klavye.png")
coffeImg = pygame.image.load("Sprites/Kahve.png")
enemyphoto = pygame.image.load("Sprites/Enemy.png")
enemyl2Img = pygame.image.load("Sprites/l2Enemy.png")
enemyl3Img = pygame.image.load ("Sprites/l3Enemy.png")
bulletImg = pygame.image.load("Sprites/Bullet.png")
gunImg = pygame.image.load("Sprites/gun.png")
redlineImg = pygame.image.load("Sprites/Redline.png")
backgroundImg = pygame.image.load("Sprites/Background.png")
enemyTurretImg = pygame.image.load("Sprites/EnemyTurret.png")
gun2Img = pygame.image.load("Sprites/Gun2.png")
RainbowBulletImg = pygame.image.load("Sprites/R-bullet.png")
glassEnemyImg = pygame.image.load("Sprites/glasspanEnemy.png")
rBulletImg = pygame.image.load("Sprites/R-bullet.png")